---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
   name: my-pvc
   labels:
     type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    
