---
apiVersion: v1
kind: Pod
metadata: 
  name: redis-pod
  labels:
   name: redis
   type: db
   author: Dilip
spec:
  containers:
     - name: myredis
       image: redis
       volumeMounts:
        - name: myvolume
          mountPath: /data/redis
  volumes:
    - name: myvolume
      emptyDir: {} 
...        
