---
apiVersion: v1
kind: Service
metadata: 
  name: httpd-service
  labels:
    type: ci-cd
    author: Dilip
spec:
 type: LoadBalancer
 ports:
   - targetPort: 80
     port: 80
     nodePort: 31111
 selector:
   type:  server
   author: Dilip   
