---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-service
  labels:
    type: ci-cd
    author: Dilip
spec:
 type: NodePort
 ports:
   - targetPort: 8080
     port: 8080
     nodePort: 30008
 selector:
   type:  ci-cd
   author: Dilip   
