---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
   name: tomcat-replicaset
   labels:
     type: appserver
     author: Dilip
spec:
 replicas: 3
 selector:
    matchLabels:
      type: appserver 

 template:
   metadata:
     name: tomcat-pod
     labels:
       type: appserver
       author: Dilip
   spec:
     containers:
       - name: mytomcat
         image: tomee
         ports:
           - containerPort: 8080
             hostPort: 8080
...               


