---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-app-deployment
  labels:
   name: postgres-app
   author: Dilip
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: postgres-app
  template:
    metadata:
      name: posgres-app-pod
      labels:
       name: postgres-app
    spec:
      containers:
        - name: my-postgres-app
          image: postgres
          env:
           - name: POSTGRES_DB
             value: mydb
           - name: POSTGRES_USER
             value: admin
           - name: POSTGRES_PASSWORD
             value: admin     
...            





































