---
apiVersion: v1
kind: Service
metadata:
   name: result-app-service
   labels:
    name: result-app
    author: Dilip
spec:
  type: LoadBalancer
  ports:
   - targetPort: 80
     port: 80   
     nodePort: 30028
  selector:
     name: result-app
...       





































