---
apiVersion: v1
kind: Service
metadata:
   name: voting-app-service
   labels:
    name: voting-app
    author: Dilip
spec:
  type: LoadBalancer
  ports:
   - targetPort: 80
     port: 80   
     nodePort: 30029
  selector:
     name: voting-app
...       





































