---
apiVersion: v1
kind: Pod
metadata: 
  name: httpd-pod
  labels:
    type: proxy
    owner: Dilip  
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: slave2
            operator: In
            values:
            - Pradeep         
  containers:
    - name: my-httpd
      image: httpd



