---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-app-deployment
  labels:
   name: postgres-app
   author: Dilip
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: postgres-app
  template:
    metadata:
      name: posgres-app-pod
      labels:
       name: postgres-app
    spec:
      containers:
        - name: my-postgres-app
          image: postgres
          env:
           - name: POSTGRES_DB
             valueFrom: 
               secretKeyRef: 
                name: postgres-secrett
                key: a  
           - name: POSTGRES_USER
             valueFrom:
               secretKeyRef:
                 name: postgres-secret
                 key: b 
           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: postgres-secret
                 key: c  
...            





































